# Generated by Django 3.0.3 on 2020-02-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_basic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='value1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='value2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basic',
            name='value3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
